/**
 * Build Script for YouTube Time Tracker
 * 
 * Concatenates all JS source files from src/ into dist/content.js
 * in the correct dependency order.
 * 
 * Usage: node build.js
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'content.js');

// Files in dependency order (later files can reference earlier ones)
const JS_FILES = [
    // 1. Shared: state, constants, utilities
    'shared/state.js',
    'shared/constants.js',
    'shared/utils.js',
    'shared/modal-utils.js',
    'shared/db.js',
    'shared/dropdown.js',

    // 2. Shorts Blocker domain
    'shorts-blocker/blocker.js',
    'shorts-blocker/mocking-screen.js',

    // 3. Stats Tracker domain
    'stats-tracker/tracking.js',
    'stats-tracker/sidebar-template.js',
    'stats-tracker/sidebar-events.js',
    'stats-tracker/sidebar-ui.js',
    'stats-tracker/fullscreen-auto-hide.js',
    'stats-tracker/smart-fullscreen.js',
    'stats-tracker/history-render.js',
    'stats-tracker/analytics-render.js',
    'stats-tracker/shortcuts.js',

    // 4. Break Reminder domain
    'break-reminder/reminder.js',

    // 5. Dislike Counter domain
    'dislike-counter/dislike-counter.js',

    // 6. Backup Reminder popup
    'shared/reminder.js',

    // 7. Initialization (must be last)
    'init/bootstrap.js',
];

// Ensure dist directory exists
if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
}

// Concatenate all files
let output = '// Auto-generated by build.js — do not edit directly\n';
output += `// Built at: ${new Date().toISOString()}\n\n`;

for (const file of JS_FILES) {
    const filePath = path.join(SRC_DIR, file);
    
    if (!fs.existsSync(filePath)) {
        console.error(`ERROR: Missing file: ${filePath}`);
        process.exit(1);
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    output += `// ─── ${file} ${'─'.repeat(Math.max(0, 60 - file.length))} \n`;
    output += content;
    output += '\n\n';
}

// --- (Previous logic for JS continues) ---

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`✅ Build complete: dist/content.js (${(fs.statSync(OUTPUT_FILE).size / 1024).toFixed(1)} KB)`);

// ─── CSS Bundle ───
const CSS_OUTPUT = path.join(DIST_DIR, 'content.css');
const CSS_FILES = [
    'src/shared/theme.css',
    'src/shared/modal.css',
    'src/shared/dropdown.css',
    'src/stats-tracker/toggle-button.css',
    'src/stats-tracker/sidebar.css',
    'src/stats-tracker/dashboard.css',
    'src/stats-tracker/charts.css',
    'src/settings/settings.css',
    'src/break-reminder/break-modal.css',
    'src/init/responsive.css'
];

let cssOutput = `/* Unified Styles Bundle — Built at: ${new Date().toISOString()} */\n\n`;
for (const file of CSS_FILES) {
    const filePath = path.join(__dirname, file);
    if (!fs.existsSync(filePath)) {
        console.error(`ERROR: Missing CSS source file: ${filePath}`);
        continue;
    }
    const content = fs.readFileSync(filePath, 'utf-8');
    cssOutput += `/* ─── ${file} ─── */\n`;
    cssOutput += content;
    cssOutput += '\n\n';
}

fs.writeFileSync(CSS_OUTPUT, cssOutput, 'utf-8');
console.log(`✅ Build complete: dist/content.css (${(fs.statSync(CSS_OUTPUT).size / 1024).toFixed(1)} KB)`);

// ─── Background Bundle ───
const BACKGROUND_OUTPUT = path.join(DIST_DIR, 'background.js');
const BACKGROUND_FILES = [
    'src/shared/db.js',
    'background.js'
];

let bgOutput = '// Auto-generated by build.js — do not edit directly\n';
bgOutput += `// Built at: ${new Date().toISOString()}\n\n`;

for (const file of BACKGROUND_FILES) {
    const filePath = path.join(__dirname, file);
    if (!fs.existsSync(filePath)) {
        console.error(`ERROR: Missing background source file: ${filePath}`);
        continue;
    }
    const content = fs.readFileSync(filePath, 'utf-8');
    bgOutput += `// ─── ${file} ${'─'.repeat(Math.max(0, 60 - file.length))} \n`;
    bgOutput += content;
    bgOutput += '\n\n';
}

fs.writeFileSync(BACKGROUND_OUTPUT, bgOutput, 'utf-8');
console.log(`✅ Build complete: dist/background.js (${(fs.statSync(BACKGROUND_OUTPUT).size / 1024).toFixed(1)} KB)`);

// Print summary details
console.log(`\n📊 Source file line counts:`);
let hasOversize = false;
for (const file of JS_FILES) {
    const filePath = path.join(SRC_DIR, file);
    const lines = fs.readFileSync(filePath, 'utf-8').split('\n').length;
    const status = lines > 300 ? '⚠️  OVER 300' : '✓';
    if (lines > 300) hasOversize = true;
    console.log(`   ${status} ${file}: ${lines} lines`);
}

if (hasOversize) {
    console.log('\n⚠️  Some files exceed 300 lines!');
} else {
    console.log('\n✅ All source files are within the 300-line limit.');
}
